# Generated by Django 5.0.3 on 2024-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='posts',
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
