# Generated by Django 5.0.3 on 2024-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='categories',
            field=models.ManyToManyField(related_name='film_categories', through='cinema.FilmCategory', to='cinema.category'),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(related_name='film_contries', through='cinema.FilmCountry', to='cinema.country'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='film_genres', through='cinema.FilmGenre', to='cinema.genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='photos',
            field=models.ManyToManyField(related_name='film_photo', through='cinema.FilmPhoto', to='cinema.photo'),
        ),
    ]
