# Generated by Django 5.0.3 on 2024-04-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_remove_member_posts_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.SlugField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
