# Generated by Django 5.0.3 on 2024-04-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_photo_image_alter_film_poster_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='film',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='film',
            name='photos',
        ),
    ]
