# Generated by Django 5.0.3 on 2024-04-23 16:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_film_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=1000, null=True),
        ),
    ]
