# Generated by Django 5.0.3 on 2024-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
