# Generated by Django 5.0.3 on 2024-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_film_url_alter_member_gender_alter_member_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='members_posts',
            field=models.ManyToManyField(related_name='member_posts', through='cinema.FilmMemberPost', to='cinema.post'),
        ),
    ]
