# Generated by Django 5.0.3 on 2024-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_member_members_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Mужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=7),
        ),
    ]
