# Generated by Django 5.0.3 on 2024-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_member_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
