# Generated by Django 5.0.3 on 2024-05-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='members_posts',
            field=models.ManyToManyField(related_name='posts', through='cinema.FilmMemberPost', to='cinema.post'),
        ),
    ]
