# Generated by Django 5.0.3 on 2024-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_photo_film_id_delete_filmphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(null=True, upload_to='media/films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='raiting',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
