# Generated by Django 5.0.3 on 2024-04-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_film_poster_alter_film_raiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='raiting',
            new_name='rating',
        ),
    ]
