# Generated by Django 5.0.3 on 2024-05-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_rename_last_name_member_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
