# Generated by Django 5.0.3 on 2024-05-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_post_name_en_post_name_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True, 'ordering': ['-id'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
    ]
