# Generated by Django 5.0.3 on 2024-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorestar',
            name='value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
