# Generated by Django 5.0.3 on 2024-05-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_scorestar_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='reviews',
            field=models.ManyToManyField(related_name='film_reviews', through='cinema.Review', to='cinema.user'),
        ),
    ]
