# Generated by Django 5.0.3 on 2024-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_alter_member_date_of_birth_alter_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Mужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('', 'Man'), ('Женщина', 'Woman')], max_length=7),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender_en',
            field=models.CharField(choices=[('Mужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('', 'Man'), ('Женщина', 'Woman')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender_ru',
            field=models.CharField(choices=[('Mужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('', 'Man'), ('Женщина', 'Woman')], max_length=7, null=True),
        ),
    ]
