# Generated by Django 5.0.3 on 2024-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_alter_member_gender_alter_member_gender_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='user/default_user_image.jpeg', null=True, upload_to='users/'),
        ),
    ]
