# Generated by Django 5.0.3 on 2024-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_alter_user_favorite_alter_user_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Mужчина', 'Мужчина'), ('Женщина', 'Женщина'), ('', 'Man'), ('Женщина', 'Woman')], max_length=7, null=True),
        ),
    ]
