# Generated by Django 5.0.3 on 2024-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
