# Generated by Django 5.0.3 on 2024-05-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_remove_user_url_film_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='user_scores',
            field=models.ManyToManyField(blank=True, related_name='film_scores', through='cinema.Score', to='cinema.user'),
        ),
    ]
