# Generated by Django 5.0.3 on 2024-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0028_alter_user_email_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/default_user_image.jpeg', null=True, upload_to='users/'),
        ),
    ]
