# Generated by Django 5.0.3 on 2024-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0030_alter_film_poster_alter_film_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
