# Generated by Django 5.0.3 on 2024-05-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='members/default_member_image.jpeg', null=True, upload_to='members/'),
        ),
    ]
