# Generated by Django 5.0.3 on 2024-05-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0032_alter_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
