# Generated by Django 5.0.3 on 2024-05-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0035_film_user_favorite_alter_film_user_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='user_favorite',
        ),
        migrations.RemoveField(
            model_name='film',
            name='user_views',
        ),
    ]
