# Generated by Django 5.0.3 on 2024-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0036_remove_film_user_favorite_remove_film_user_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='user_favorite',
            field=models.ManyToManyField(blank=True, related_name='film_favorite', to='cinema.user'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='films/default_film_i mage.jpg', null=True, upload_to='films/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='reviews',
            field=models.ManyToManyField(related_name='user_reviews', through='cinema.Review', to='cinema.user'),
        ),
    ]
