# Generated by Django 5.0.3 on 2024-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0037_film_user_favorite_alter_film_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='user_views',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='cinema.user'),
        ),
    ]
