# Generated by Django 5.0.3 on 2024-05-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0039_rename_release_date_russia_film_release_russia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='release_russia',
            new_name='release_date_russia',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='release_world',
            new_name='release_date_world',
        ),
    ]
