# Generated by Django 5.0.3 on 2024-05-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0040_rename_release_russia_film_release_date_russia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
