# Generated by Django 5.0.3 on 2024-05-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0041_remove_film_categories_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, default='films/default_film_image.jpg', null=True, upload_to='films/'),
        ),
    ]
